server.port: 7002
server.error.include-message: always

spring:
  cloud:
    function:
      definition: deleteProduct
    stream:
      defaultBinder: rabbit
      default:
        contentType: application/json
      bindings:
        deleteProduct-in-0:
          destination: deleteProduct
          group: consumers1Group
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 500
            backOffMaxInterval: 1000
            backOffMultiplier: 2.0
#            partitioned: true
#            instanceCount: 2
#            instanceIndex: 0
      rabbit:
        bindings:
          createProduct-in-0:
            consumer:
              autoBindDlq: true
              republishToDlq: true
      kafka:
        binder:
          brokers: 127.0.0.1
          defaultBrokerPort: 9092
        bindings:
          createProduct-in-0:
            consumer:
              enableDlq: true

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

logging:
  level:
    root: INFO

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
